In [1]:
import numpy as np 
import pandas as pd
from pandas import Series, DataFrame
from sklearn.preprocessing import StandardScaler

## Import and aggregate data

In [24]:
data = pd.read_excel('X_non_district_senate.xlsx', na_values = 'NA')
data1 = data.dropna(axis = 0)

y = data1.iloc[:, -3::]
x = data1.iloc[:, 2:-3]

In [25]:
x['Age - 18 to 34'] = x['Total population - AGE - 20 to 24 years'] +\
                         x['Total; Estimate; Total population - AGE - 25 to 29 years'] +\
                         x['Total; Estimate; Total population - AGE - 30 to 34 years']

x['Age - 35 to 49'] = x['Total; Estimate; Total population - AGE - 35 to 39 years'] +\
                         x['Total; Estimate; Total population - AGE - 40 to 44 years'] +\
                         x['Total; Estimate; Total population - AGE - 45 to 49 years']
                         
x['Age - over 50'] = x['Total; Estimate; Total population - AGE - 50 to 54 years'] +\
                         x['Total; Estimate; Total population - AGE - 55 to 59 years'] +\
                         x['Total; Estimate; Total population - AGE - 60 to 64 years'] +\
                         x['Total; AGE voer 65']

x['Income - 10k to 35k'] = x['Households; Estimate; Less than $10,000'] +\
                         x['Households; Estimate; $10,000 to $14,999'] +\
                         x['Households; Estimate; $15,000 to $24,999'] +\
                         x['Households; Estimate; $25,000 to $34,999']

x['Income - 35k to 100k'] = x['Households; Estimate; $35,000 to $49,999'] +\
                         x['Households; Estimate; $50,000 to $74,999'] +\
                         x['Households; Estimate; $75,000 to $99,999']
                         
x['Income - over 100k'] = x['Households; Estimate; $100,000 to $149,999'] +\
                         x['Households; Estimate; $150,000 to $199,999'] +\
                         x['Households; Estimate; $200,000 or more'] 

x['Race - White'] = x['Population of one race: - White alone']
x['Race - Black'] = x['Population of one race: - Black or African American alone']
x['Race - Asian and Others'] = x['Population of one race: - Asian alone'] +\
                              x['Population of one race: - American Indian and Alaska Native alone'] +\
                              x['Population of one race: - Native Hawaiian and Other Pacific Islander alone']

x['Education - Below High School'] = x['Estimate; Less than high school graduate'] +\
                                     x['Estimate; High school graduate (includes equivalency)']
x['Education - Above College'] = x['Estimate; Some college or associate degree'] +\
                                 x['Estimate; Bachelor degree']
x['Education - Above Graduate'] = x["Estimate; Graduate or professional degree"]

In [26]:
# select desired attributes
x_sim = x.iloc[:, 54::]
x_sim.index = np.arange(0, 12)
y.index = np.arange(0, 12)

## Normalization

In [27]:
x_numeric = x_sim.iloc[:, 4::]
x_categoric = x_sim.iloc[:, 0:4]
scaler = StandardScaler().fit(x_numeric)
x_normalize = scaler.transform(x_numeric)
x_normalize = pd.concat([x_categoric, DataFrame(x_normalize, columns=x_numeric.columns)], axis=1)

In [28]:
x_2018 = x_normalize.iloc[11, ::]
x_normalize = x_normalize.drop(index=11)
y = y.drop(index=11)

## Train & Test split

In [52]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_normalize, y, test_size=0.1, random_state=None)

In [57]:
x_train

,presidency_demo,governeor_demo,state_MN,state_WI,pre_gdp,gdp,Poverty,Senate_demo,Senate_republic,MD_Rasmussen Reports_democratic,...,Age - over 50,Income - 10k to 35k,Income - 35k to 100k,Income - over 100k,Race - White,Race - Black,Race - Asian and Others,Education - Below High School,Education - Above College,Education - Above Graduate
4,1,0,0,1,0.276816,0.324416,1.374795,0.123484,-0.080569,-0.391911,...,0.319498,1.459609,1.252421,-0.095382,1.005078,0.963203,-0.152087,1.584339,0.406979,0.178578
8,1,1,0,0,-1.525963,-1.507559,0.887183,-0.681451,0.756110,-1.577522,...,-1.289156,-0.948488,-1.283182,-1.324697,-1.358744,-1.153431,-1.192738,-1.244858,-1.296924,-1.208173
1,1,0,1,0,0.644048,0.616887,-1.550877,2.154116,-2.144379,-1.314053,...,-0.349231,0.262440,0.776552,0.311768,0.540634,-0.052089,0.534826,0.272139,0.407753,0.259721
0,0,0,1,0,0.644048,0.577397,-1.388340,1.605297,-1.567999,0.925436,...,0.340415,0.550871,0.697145,-0.143345,0.344401,-0.236330,0.532875,0.054920,0.346023,0.212236
2,1,1,1,0,0.727510,0.732883,-0.088041,0.251542,-0.210719,1.452375,...,0.126867,0.401794,0.613654,0.623556,0.548669,0.424129,1.006651,0.123637,0.790236,0.737651
3,1,1,1,0,0.877742,0.950216,-0.006772,-0.022867,-0.210719,0.266763,...,1.378113,0.169010,0.574560,1.059343,0.568474,0.561475,1.189688,0.081270,0.911413,1.005752
9,1,0,0,0,-1.342347,-1.293359,0.562108,-0.882685,0.960632,0.095508,...,-1.134128,-1.192662,-1.321266,-0.982724,-1.411996,-1.385710,-1.358067,-1.246334,-1.394052,-1.443054
5,1,0,0,1,0.460432,0.469134,1.374795,-0.425335,0.477217,-0.260176,...,0.524038,1.482921,-0.474535,0.076231,0.986512,1.115173,-0.040743,1.474173,0.574283,0.455170
6,1,0,0,1,0.694126,0.688034,0.237034,0.690598,-0.656948,0.003293,...,0.857130,0.957812,1.218488,0.782548,0.970232,1.166415,0.274629,1.209612,0.897653,0.684305

## Feature Selection

In [72]:
# Univariate feature selection
from sklearn.feature_selection import SelectKBest, f_regression

In [113]:
x_numeric, x_categoric = x_train.iloc[:, 17::], x_train.iloc[:, 0:17]

# K best numerical features
selector = SelectKBest(f_regression, k=int(x_numeric.shape[1]/2)).fit(x_numeric, y_train.iloc[:, 0])
print("K best features: ", x_numeric.columns[selector.get_support()])

x_train_fs = x_numeric.iloc[:, SKB.get_support(indices=True)]
x_train_fs = pd.concat([x_categoric, x_train_fs], axis=1)

K best features:  Index(['Income - 10k to 35k', 'Race - White', 'Race - Black',
       'Education - Below High School', 'Education - Above College',
       'Education - Above Graduate'],
      dtype='object')

In [105]:
x_numeric, x_categoric = x_test.iloc[:, 17::], x_test.iloc[:, 0:17]
x_test_fs = x_numeric.iloc[:, SKB.get_support(indices=True)]
x_test_fs = pd.concat([x_categoric, x_test_fs], axis=1)
x_test_fs.index = np.arange(0, 2)

In [125]:
y_train

   senate_republican  senate_democratic  senate_third-part
4          1125999.0          1020958.0            34000.0
8           718215.0           371686.0            25290.0
1          1212317.0          1212629.0            82265.5
0           835653.0          1278849.0            87316.0
2           867974.0          1854595.0           118056.0
3           850227.0          1053205.0            77215.0
9           588575.0           494370.0            45644.0
5          1380126.0          1547104.0            78695.0
6          1479471.0          1380355.0            87531.0

## Modelling with Feature Selection

In [33]:
# MultiOutputRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import Ridge
from sklearn.svm import SVR
from sklearn import linear_model
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [34]:
# Grid Search
from sklearn.model_selection import GridSearchCV

# cross val score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_absolute_error

In [110]:
# for cross validation
X = pd.concat([x_train_fs, x_test_fs], axis=0)
Y = pd.concat([y_train, y_test], axis=0)

### Grid Search and Cross-Validation

In [148]:
parameters = [
    {'estimator__alpha': [1, 1e1, 1e2, 1e3, 1e4, 1e5], 'estimator__solver': ['svd', 'cholesky', 'sag']},
    {'estimator__kernel': ['linear', 'rbf'], 'estimator__C': [1, 1e1, 1e2, 1e3, 1e4, 1e5, 1e6, 1e7],\
     'estimator__epsilon': [1e-4, 1e-3, 1e-2, 1e-1, 1, 1e1, 1e2, 1e3]},
    {'estimator__alpha_1': [1e-4, 1e-5, 1e-6, 1e-7, 1e-8], 'estimator__alpha_2': [1e-4, 1e-5, 1e-6, 1e-7, 1e-8],\
     'estimator__lambda_1': [1e-4, 1e-5, 1e-6, 1e-7, 1e-8], 'estimator__lambda_2': [1e-4, 1e-5, 1e-6, 1e-7, 1e-8]},
    {'estimator__bootstrap': ['True', 'False'], 'estimator__max_features': ['auto', 'sqrt', 'log2'],\
     'estimator__min_samples_split': [2, 3, 4, 5, 6], 'estimator__min_samples_leaf': [1, 2, 3, 4, 5]},
    {'estimator__n_estimators': [25, 50, 100], 'estimator__loss': ['ls', 'lad'],
     'estimator__max_depth': [2, 3, 4, 5, 6], 'estimator__learning_rate': [1e-4, 1e-3, 1e-2, 1e-1], 'estimator__subsample': [0.2, 0.4, 0.6, 0.8, 1.0]},
    {'estimator__algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'], 'estimator__weights': ['uniform', 'distance']}
]
models = [Ridge(), SVR(), linear_model.BayesianRidge(), RandomForestRegressor(), GradientBoostingRegressor(), KNeighborsRegressor()]

record = []
#prediction = []

for i, model in enumerate(models):
    regressor = model
    # grid search
    gridcv = GridSearchCV(MultiOutputRegressor(regressor), parameters[i], cv=5, scoring = 'neg_mean_absolute_error')
    gridcv.fit(x_train_fs, y_train)
    # mae
    mae_train, mae_test = mean_absolute_error(y_train, gridcv.predict(x_train_fs), multioutput = 'uniform_average'),\
                            mean_absolute_error(y_test, gridcv.predict(x_test_fs), multioutput = 'uniform_average')
    # cv 
    score = cross_val_score(gridcv.best_estimator_, X, Y, cv=5, scoring = 'neg_mean_absolute_error')
    cv_mean, cv_std = np.mean(score).round(), np.std(score).round()
    
    #prediction += gridcv.predict(x_test_fs)
    record.append([model, mae_train, mae_test, -cv_mean, cv_std])

df = DataFrame(data=record, columns=['Model', 'MAE_Train', 'MAE_Test', 'CV_mean', 'CV_std'])

ValueError: operands could not be broadcast together with shapes (0,) (2,3)

In [143]:
df

,Model,MAE_Train,MAE_Test,CV_mean,CV_std
0,"Ridge(alpha=1.0, copy_X=True, fit_intercept=Tr...",88318.677980,87074.989271,171020.0,52511.0
1,"SVR(C=1.0, cache_size=200, coef0=0.0, degree=3...",85935.524685,95661.299689,175720.0,63052.0
2,"BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, co...",72552.193109,93176.007878,196112.0,55775.0
3,"RandomForestRegressor(bootstrap=True, criterio...",95194.931543,165792.202778,213111.0,68609.0
4,"GradientBoostingRegressor(alpha=0.9, criterion...",40059.937360,136927.703306,180337.0,73403.0
5,"KNeighborsRegressor(algorithm='auto', leaf_siz...",0.000000,164725.599675,187127.0,33702.0

## Modelling with PCA

### PCA